name:                player-hs
version:             0.1.0.0
github:              "aieis/player-hs"
license:             BSD3
author:              "Ahmed Salem"
maintainer:          "aieisalem17@gmail.com"
copyright:           "2023 Ahmed Salem"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cv#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- word8
- hip
- random
- haskell-gi
- haskell-gi-base
- gi-gtk
- gi-gdkpixbuf
  
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  player-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - player-hs

tests:
  player-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - player-hs
